name: Build and Push Docker Image

on:
  workflow_dispatch: # manual trigger
  push:
    branches: ["main"] # build on code push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

        # Lint Dockerfile
      - name: Lint Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./app/Dockerfile

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print Docker version and info
        run: |
          echo "ðŸ³ Docker Version:"
          docker version
          echo "ðŸ—ï¸ Builder Info:"
          docker buildx ls

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./app
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{vars.DOCKERHUB_REPO}}:latest,${{ secrets.DOCKERHUB_USERNAME }}/${{vars.DOCKERHUB_REPO}}:${{ github.sha }}

      - name: Image digest
        run: |
          echo "ðŸš€ Image digest: ${{ steps.docker_build.outputs.digest }}"

      - name: Build Summary
        run: |
          echo "### Build Complete! ðŸŽ‰" >> $GITHUB_STEP_SUMMARY
          echo "* Repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{vars.DOCKERHUB_REPO}}" >> $GITHUB_STEP_SUMMARY
          echo "* Tags: latest, ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "* Digest: ${{ steps.docker_build.outputs.digest }}" >> $GITHUB_STEP_SUMMARY
